/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'dgc' at '9/12/16 12:07 AM' with Gradle 3.0
 *
 * @author dgc, @date 9/12/16 12:07 AM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
