/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'dgc' at '9/12/16 12:07 AM' with Gradle 3.0
 *
 * @author dgc, @date 9/12/16 12:07 AM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
