#!/bin/bash


USER="utc"
case "$1" in
    start)
	su ${USER} -s /bin/bash -c "/opt/utc/start_server.sh"
	;;

    stop)
	su ${USER} -s /bin/bash -c "/opt/utc/stop_server.sh"
	;;

    restart)
        $0 stop
    	$0 start
    ;;
esac
