/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'dgc' at '9/8/16 8:50 PM' with Gradle 3.0
 *
 * @author dgc, @date 9/8/16 8:50 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
